services:
  postgres:
    env_file:
      - ./backend/.env.development
    ports:
      - "6432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/18/docker

  pgbouncer:
    env_file:
      - ./backend/.env.development

volumes:
  postgres_data_dev: